In [1]:
import math
import numpy as np
import pandas as pd
from collections import Counter

In [2]:
np.random.seed(seed=408)

In [3]:
# 1) create dictionary for each nba team
# 2) write function to append updated elo to each team dictionary
# 3) write function to take in file of all games to be played and loop through them and update team dictionary

In [4]:
# Create df with team name, wins, losses, elo
team_df = pd.read_csv("C:\\Users\\Divya Parmar's PC\\Documents\\NBA-Predictions-2020-Restart\\nba_elo_data.csv")

In [5]:
# Create weighed elo value to estimate team's true ability
# Weigh between current elo value and potential full strength elo
# Use 0.5 meaning we give half credit to current and full strength
elo_weight_start_season = 0.5

In [9]:
# Officially create weighed elo value to estimate team's true ability
team_df['elo_value'] = elo_weight_start_season * team_df['elo_basic'] + (1 - elo_weight_start_season) * team_df['elo_playoff_full']

In [10]:
team_df['elo_list'] = [[x] for x in team_df.elo_value]

In [11]:
#Create copies of dataframe
team_df_testing = team_df
team_df_backup = team_df

In [12]:
#Bring in the schedule
schedule = pd.read_csv("C:\\Users\\Divya Parmar's PC\\Documents\\NBA-Predictions-2020-Restart\\nba_regular_season_games_2020.csv")

In [13]:
# Look at our dataframe
team_df

,team_abbrev,team_nickname,elo_basic,elo_playoff_full,wins,losses,conference,elo_value,elo_list
0,LAL,Lakers,1678,1710,49,14,western,1694.0,[1694.0]
1,LAC,Clippers,1636,1732,44,20,western,1684.0,[1684.0]
2,MIL,Bucks,1716,1694,53,12,eastern,1705.0,[1705.0]
3,PHI,76ers,1564,1691,39,26,eastern,1627.5,[1627.5]
4,HOU,Rockets,1565,1701,40,24,western,1633.0,[1633.0]
5,BOS,Celtics,1628,1682,43,21,eastern,1655.0,[1655.0]
6,TOR,Raptors,1679,1628,46,18,eastern,1653.5,[1653.5]
7,DEN,Nuggets,1579,1638,43,22,western,1608.5,[1608.5]
8,OKC,Thunder,1608,1583,40,24,western,1595.5,[1595.5]
9,DAL,Mavericks,1584,1643,40,27,western,1613.5,[1613.5]
10,NOP,Pelicans,1542,1611,28,36,western,1576.5,[1576.5]
11,UTA,Jazz,1574,1584,41,23,western,1579.0,[1579.0]
12,MIA,Heat,1553,1534,41,24,eastern,1543.5,[1543.5]
13,IND,Pacers,1560,1586,39,26,eastern,1573.0,[1573.0]
14,POR,Trailblazers,1490,1569,29,37,western,1529.5,[1529.5]
15,ORL,Magic,1503,1546,30,35,eastern,1524.5,[1524.5]
16,BKN,Nets,1478,1560,30,34,eastern,1519.0,[1519.0]
17,MEM,Grizzlies,1553,1456,32,33,western,1504.5,[1504.5]
18,SAC,Kings,1509,1512,28,36,western,1510.5,[1510.5]
19,SAS,Spurs,1499,1473,27,36,western,1486.0,[1486.0]
20,WAS,Wizards,1396,1432,24,40,eastern,1414.0,[1414.0]
21,PHX,Suns,1454,1520,26,39,western,1487.0,[1487.0]

In [14]:
team_df

,team_abbrev,team_nickname,elo_basic,elo_playoff_full,wins,losses,conference,elo_value,elo_list
0,LAL,Lakers,1678,1710,49,14,western,1694.0,[1694.0]
1,LAC,Clippers,1636,1732,44,20,western,1684.0,[1684.0]
2,MIL,Bucks,1716,1694,53,12,eastern,1705.0,[1705.0]
3,PHI,76ers,1564,1691,39,26,eastern,1627.5,[1627.5]
4,HOU,Rockets,1565,1701,40,24,western,1633.0,[1633.0]
5,BOS,Celtics,1628,1682,43,21,eastern,1655.0,[1655.0]
6,TOR,Raptors,1679,1628,46,18,eastern,1653.5,[1653.5]
7,DEN,Nuggets,1579,1638,43,22,western,1608.5,[1608.5]
8,OKC,Thunder,1608,1583,40,24,western,1595.5,[1595.5]
9,DAL,Mavericks,1584,1643,40,27,western,1613.5,[1613.5]
10,NOP,Pelicans,1542,1611,28,36,western,1576.5,[1576.5]
11,UTA,Jazz,1574,1584,41,23,western,1579.0,[1579.0]
12,MIA,Heat,1553,1534,41,24,eastern,1543.5,[1543.5]
13,IND,Pacers,1560,1586,39,26,eastern,1573.0,[1573.0]
14,POR,Trailblazers,1490,1569,29,37,western,1529.5,[1529.5]
15,ORL,Magic,1503,1546,30,35,eastern,1524.5,[1524.5]
16,BKN,Nets,1478,1560,30,34,eastern,1519.0,[1519.0]
17,MEM,Grizzlies,1553,1456,32,33,western,1504.5,[1504.5]
18,SAC,Kings,1509,1512,28,36,western,1510.5,[1510.5]
19,SAS,Spurs,1499,1473,27,36,western,1486.0,[1486.0]
20,WAS,Wizards,1396,1432,24,40,eastern,1414.0,[1414.0]
21,PHX,Suns,1454,1520,26,39,western,1487.0,[1487.0]

In [15]:
# Look at schedule
schedule

   team_a team_b
0     UTA    NOP
1     LAC    LAL
2     ORL    BKN
3     ORL    BKN
4     MEM    POR
5     PHX    WAS
6     BOS    MIL
7     SAC    SAS
8     HOU    DAL
9     MIA    DEN
10    UTA    OKC
11    NOP    LAC
12    PHI    IND
13    LAL    TOR
14    WAS    BKN
15    POR    BOS
16    SAS    MEM
17    SAC    ORL
18    MIL    HOU
19    DAL    PHX
20    TOR    MIA
21    DEN    OKC
22    IND    WAS
23    MEM    NOP
24    SAS    PHI
25    LAL    UTA
26    BKN    MIL
27    DAL    SAC
28    PHX    LAC
29    ORL    IND
..    ...    ...
59    PHI    POR
60    HOU    SAC
61    BKN    LAC
62    OKC    PHX
63    DAL    UTA
64    TOR    MIL
65    IND    MIA
66    DEN    LAL
67    BKN    ORL
68    HOU    SAS
69    PHX    PHI
70    POR    DAL
71    BOS    MEM
72    NOP    SAC
73    MIL    WAS
74    IND    HOU
75    TOR    PHI
76    MIA    OKC
77    LAC    DEN
78    WAS    BOS
79    POR    BKN
80    SAC    LAL
81    MIL    MEM
82    NOP    ORL
83    DAL    PHX
84    SAS    UTA
85    PHI    HOU
86    MIA    IND
87    OKC    LAC
88    DEN    TOR

[89 rows x 2 columns]

In [16]:
team_df.to_dict(orient='index')

{0: {'conference': 'western',
  'elo_basic': 1678L,
  'elo_list': [1694.0],
  'elo_playoff_full': 1710L,
  'elo_value': 1694.0,
  'losses': 14L,
  'team_abbrev': 'LAL',
  'team_nickname': 'Lakers',
  'wins': 49L},
 1: {'conference': 'western',
  'elo_basic': 1636L,
  'elo_list': [1684.0],
  'elo_playoff_full': 1732L,
  'elo_value': 1684.0,
  'losses': 20L,
  'team_abbrev': 'LAC',
  'team_nickname': 'Clippers',
  'wins': 44L},
 2: {'conference': 'eastern',
  'elo_basic': 1716L,
  'elo_list': [1705.0],
  'elo_playoff_full': 1694L,
  'elo_value': 1705.0,
  'losses': 12L,
  'team_abbrev': 'MIL',
  'team_nickname': 'Bucks',
  'wins': 53L},
 3: {'conference': 'eastern',
  'elo_basic': 1564L,
  'elo_list': [1627.5],
  'elo_playoff_full': 1691L,
  'elo_value': 1627.5,
  'losses': 26L,
  'team_abbrev': 'PHI',
  'team_nickname': '76ers',
  'wins': 39L},
 4: {'conference': 'western',
  'elo_basic': 1565L,
  'elo_list': [1633.0],
  'elo_playoff_full': 1701L,
  'elo_value': 1633.0,
  'losses': 24L,
  'team_abbrev': 'HOU',
  'team_nickname': 'Rockets',
  'wins': 40L},
 5: {'conference': 'eastern',
  'elo_basic': 1628L,
  'elo_list': [1655.0],
  'elo_playoff_full': 1682L,
  'elo_value': 1655.0,
  'losses': 21L,
  'team_abbrev': 'BOS',
  'team_nickname': 'Celtics',
  'wins': 43L},
 6: {'conference': 'eastern',
  'elo_basic': 1679L,
  'elo_list': [1653.5],
  'elo_playoff_full': 1628L,
  'elo_value': 1653.5,
  'losses': 18L,
  'team_abbrev': 'TOR',
  'team_nickname': 'Raptors',
  'wins': 46L},
 7: {'conference': 'western',
  'elo_basic': 1579L,
  'elo_list': [1608.5],
  'elo_playoff_full': 1638L,
  'elo_value': 1608.5,
  'losses': 22L,
  'team_abbrev': 'DEN',
  'team_nickname': 'Nuggets',
  'wins': 43L},
 8: {'conference': 'western',
  'elo_basic': 1608L,
  'elo_list': [1595.5],
  'elo_playoff_full': 1583L,
  'elo_value': 1595.5,
  'losses': 24L,
  'team_abbrev': 'OKC',
  'team_nickname': 'Thunder',
  'wins': 40L},
 9: {'conference': 'western',
  'elo_basic': 1584L,
  'elo_list': [1613.5],
  'elo_playoff_full': 1643L,
  'elo_value': 1613.5,
  'losses': 27L,
  'team_abbrev': 'DAL',
  'team_nickname': 'Mavericks',
  'wins': 40L},
 10: {'conference': 'western',
  'elo_basic': 1542L,
  'elo_list': [1576.5],
  'elo_playoff_full': 1611L,
  'elo_value': 1576.5,
  'losses': 36L,
  'team_abbrev': 'NOP',
  'team_nickname': 'Pelicans',
  'wins': 28L},
 11: {'conference': 'western',
  'elo_basic': 1574L,
  'elo_list': [1579.0],
  'elo_playoff_full': 1584L,
  'elo_value': 1579.0,
  'losses': 23L,
  'team_abbrev': 'UTA',
  'team_nickname': 'Jazz',
  'wins': 41L},
 12: {'conference': 'eastern',
  'elo_basic': 1553L,
  'elo_list': [1543.5],
  'elo_playoff_full': 1534L,
  'elo_value': 1543.5,
  'losses': 24L,
  'team_abbrev': 'MIA',
  'team_nickname': 'Heat',
  'wins': 41L},
 13: {'conference': 'eastern',
  'elo_basic': 1560L,
  'elo_list': [1573.0],
  'elo_playoff_full': 1586L,
  'elo_value': 1573.0,
  'losses': 26L,
  'team_abbrev': 'IND',
  'team_nickname': 'Pacers',
  'wins': 39L},
 14: {'conference': 'western',
  'elo_basic': 1490L,
  'elo_list': [1529.5],
  'elo_playoff_full': 1569L,
  'elo_value': 1529.5,
  'losses': 37L,
  'team_abbrev': 'POR',
  'team_nickname': 'Trailblazers',
  'wins': 29L},
 15: {'conference': 'eastern',
  'elo_basic': 1503L,
  'elo_list': [1524.5],
  'elo_playoff_full': 1546L,
  'elo_value': 1524.5,
  'losses': 35L,
  'team_abbrev': 'ORL',
  'team_nickname': 'Magic',
  'wins': 30L},
 16: {'conference': 'eastern',
  'elo_basic': 1478L,
  'elo_list': [1519.0],
  'elo_playoff_full': 1560L,
  'elo_value': 1519.0,
  'losses': 34L,
  'team_abbrev': 'BKN',
  'team_nickname': 'Nets',
  'wins': 30L},
 17: {'conference': 'western',
  'elo_basic': 1553L,
  'elo_list': [1504.5],
  'elo_playoff_full': 1456L,
  'elo_value': 1504.5,
  'losses': 33L,
  'team_abbrev': 'MEM',
  'team_nickname': 'Grizzlies',
  'wins': 32L},
 18: {'conference': 'western',
  'elo_basic': 1509L,
  'elo_list': [1510.5],
  'elo_playoff_full': 1512L,
  'elo_value': 1510.5,
  'losses': 36L,
  'team_abbrev': 'SAC',
  'team_nickname': 'Kings',
  'wins': 28L},
 19: {'conference': 'western',
  'elo_basic': 1499L,
  'elo_list': [1486.0],
  'elo_playoff_full': 1473L,
  'elo_value': 1486.0,
  'losses': 36L,
  'team_abbrev': 'SAS',
  'team_nickname': 'Spurs',
  'wins': 27L},
 20: {'conference': 'eastern',
  'elo_basic': 1396L,
  'elo_list': [1414.0],
  'elo_playoff_full': 1432L,
  'elo_value': 1414.0,
  'losses': 40L,
  'team_abbrev': 'WAS',
  'team_nickname': 'Wizards',
  'wins': 24L},
 21: {'conference': 'western',
  'elo_basic': 1454L,
  'elo_list': [1487.0],
  'elo_playoff_full': 1520L,
  'elo_value': 1487.0,
  'losses': 39L,
  'team_abbrev': 'PHX',
  'team_nickname': 'Suns',
  'wins': 26L}}

In [17]:
team_df.to_dict(orient='records')

[{'conference': 'western',
  'elo_basic': 1678L,
  'elo_list': [1694.0],
  'elo_playoff_full': 1710L,
  'elo_value': 1694.0,
  'losses': 14L,
  'team_abbrev': 'LAL',
  'team_nickname': 'Lakers',
  'wins': 49L},
 {'conference': 'western',
  'elo_basic': 1636L,
  'elo_list': [1684.0],
  'elo_playoff_full': 1732L,
  'elo_value': 1684.0,
  'losses': 20L,
  'team_abbrev': 'LAC',
  'team_nickname': 'Clippers',
  'wins': 44L},
 {'conference': 'eastern',
  'elo_basic': 1716L,
  'elo_list': [1705.0],
  'elo_playoff_full': 1694L,
  'elo_value': 1705.0,
  'losses': 12L,
  'team_abbrev': 'MIL',
  'team_nickname': 'Bucks',
  'wins': 53L},
 {'conference': 'eastern',
  'elo_basic': 1564L,
  'elo_list': [1627.5],
  'elo_playoff_full': 1691L,
  'elo_value': 1627.5,
  'losses': 26L,
  'team_abbrev': 'PHI',
  'team_nickname': '76ers',
  'wins': 39L},
 {'conference': 'western',
  'elo_basic': 1565L,
  'elo_list': [1633.0],
  'elo_playoff_full': 1701L,
  'elo_value': 1633.0,
  'losses': 24L,
  'team_abbrev': 'HOU',
  'team_nickname': 'Rockets',
  'wins': 40L},
 {'conference': 'eastern',
  'elo_basic': 1628L,
  'elo_list': [1655.0],
  'elo_playoff_full': 1682L,
  'elo_value': 1655.0,
  'losses': 21L,
  'team_abbrev': 'BOS',
  'team_nickname': 'Celtics',
  'wins': 43L},
 {'conference': 'eastern',
  'elo_basic': 1679L,
  'elo_list': [1653.5],
  'elo_playoff_full': 1628L,
  'elo_value': 1653.5,
  'losses': 18L,
  'team_abbrev': 'TOR',
  'team_nickname': 'Raptors',
  'wins': 46L},
 {'conference': 'western',
  'elo_basic': 1579L,
  'elo_list': [1608.5],
  'elo_playoff_full': 1638L,
  'elo_value': 1608.5,
  'losses': 22L,
  'team_abbrev': 'DEN',
  'team_nickname': 'Nuggets',
  'wins': 43L},
 {'conference': 'western',
  'elo_basic': 1608L,
  'elo_list': [1595.5],
  'elo_playoff_full': 1583L,
  'elo_value': 1595.5,
  'losses': 24L,
  'team_abbrev': 'OKC',
  'team_nickname': 'Thunder',
  'wins': 40L},
 {'conference': 'western',
  'elo_basic': 1584L,
  'elo_list': [1613.5],
  'elo_playoff_full': 1643L,
  'elo_value': 1613.5,
  'losses': 27L,
  'team_abbrev': 'DAL',
  'team_nickname': 'Mavericks',
  'wins': 40L},
 {'conference': 'western',
  'elo_basic': 1542L,
  'elo_list': [1576.5],
  'elo_playoff_full': 1611L,
  'elo_value': 1576.5,
  'losses': 36L,
  'team_abbrev': 'NOP',
  'team_nickname': 'Pelicans',
  'wins': 28L},
 {'conference': 'western',
  'elo_basic': 1574L,
  'elo_list': [1579.0],
  'elo_playoff_full': 1584L,
  'elo_value': 1579.0,
  'losses': 23L,
  'team_abbrev': 'UTA',
  'team_nickname': 'Jazz',
  'wins': 41L},
 {'conference': 'eastern',
  'elo_basic': 1553L,
  'elo_list': [1543.5],
  'elo_playoff_full': 1534L,
  'elo_value': 1543.5,
  'losses': 24L,
  'team_abbrev': 'MIA',
  'team_nickname': 'Heat',
  'wins': 41L},
 {'conference': 'eastern',
  'elo_basic': 1560L,
  'elo_list': [1573.0],
  'elo_playoff_full': 1586L,
  'elo_value': 1573.0,
  'losses': 26L,
  'team_abbrev': 'IND',
  'team_nickname': 'Pacers',
  'wins': 39L},
 {'conference': 'western',
  'elo_basic': 1490L,
  'elo_list': [1529.5],
  'elo_playoff_full': 1569L,
  'elo_value': 1529.5,
  'losses': 37L,
  'team_abbrev': 'POR',
  'team_nickname': 'Trailblazers',
  'wins': 29L},
 {'conference': 'eastern',
  'elo_basic': 1503L,
  'elo_list': [1524.5],
  'elo_playoff_full': 1546L,
  'elo_value': 1524.5,
  'losses': 35L,
  'team_abbrev': 'ORL',
  'team_nickname': 'Magic',
  'wins': 30L},
 {'conference': 'eastern',
  'elo_basic': 1478L,
  'elo_list': [1519.0],
  'elo_playoff_full': 1560L,
  'elo_value': 1519.0,
  'losses': 34L,
  'team_abbrev': 'BKN',
  'team_nickname': 'Nets',
  'wins': 30L},
 {'conference': 'western',
  'elo_basic': 1553L,
  'elo_list': [1504.5],
  'elo_playoff_full': 1456L,
  'elo_value': 1504.5,
  'losses': 33L,
  'team_abbrev': 'MEM',
  'team_nickname': 'Grizzlies',
  'wins': 32L},
 {'conference': 'western',
  'elo_basic': 1509L,
  'elo_list': [1510.5],
  'elo_playoff_full': 1512L,
  'elo_value': 1510.5,
  'losses': 36L,
  'team_abbrev': 'SAC',
  'team_nickname': 'Kings',
  'wins': 28L},
 {'conference': 'western',
  'elo_basic': 1499L,
  'elo_list': [1486.0],
  'elo_playoff_full': 1473L,
  'elo_value': 1486.0,
  'losses': 36L,
  'team_abbrev': 'SAS',
  'team_nickname': 'Spurs',
  'wins': 27L},
 {'conference': 'eastern',
  'elo_basic': 1396L,
  'elo_list': [1414.0],
  'elo_playoff_full': 1432L,
  'elo_value': 1414.0,
  'losses': 40L,
  'team_abbrev': 'WAS',
  'team_nickname': 'Wizards',
  'wins': 24L},
 {'conference': 'western',
  'elo_basic': 1454L,
  'elo_list': [1487.0],
  'elo_playoff_full': 1520L,
  'elo_value': 1487.0,
  'losses': 39L,
  'team_abbrev': 'PHX',
  'team_nickname': 'Suns',
  'wins': 26L}]

In [20]:
# First let's write a function to calculate elo
# Thankfully it's  already been done
# https://www.geeksforgeeks.org/elo-rating-algorithm/

In [21]:
def elo_probability(rating1, rating2):
    return 1.0 * 1.0 / (1 + 1.0 * math.pow(10, 1.0 * (rating2 - rating1)/400))

In [22]:
# Validate that the probabilities add up to 1 for a given matchup
elo_probability(2000, 1200) + elo_probability(1200, 2000)

1.0

In [23]:
elo_probability(1200, 2000)

0.009900990099009901

In [24]:
# K-Factor determines how quickly elo score reacts to new events
# FiveThirtyEight recommends k-factor of 20 for NBA games
k = 20

In [25]:
def game_winner(rating1, rating2):
    prob = elo_probability(rating1, rating2)
    random_value = np.random.uniform(0,1)
    if random_value <= prob:
        return 1
    else:
        return 2

In [21]:
# Unit test of game_winner function
game_winner(1800, 1700)

1

In [26]:
def elo_update(rating_a, rating_b):
    Pa = elo_probability(rating_a, rating_b)
    Pb = elo_probability(rating_b, rating_a)
    
    game_winner_output = game_winner(rating_a, rating_b)
    
    if game_winner_output == 1:
        rating_a_updated = rating_a + 20 * (1-Pa)
        rating_b_updated = rating_b + 20 * (0-Pb)
    
    elif game_winner_output == 2:
        rating_a_updated = rating_a + 20 * (0-Pa)
        rating_b_updated = rating_b + 20 * (1-Pb)
    
    else:
        rating_a_updated = rating_a
        rating_b_updated = rating_b
    return rating_a_updated, rating_b_updated, game_winner_output

In [27]:
# Unit test elo_update
test_elo_a, test_elo_b, winner = elo_update(1800, 1700)
print(test_elo_a, test_elo_b, winner)

(1807.1987000039423, 1692.8012999960577, 1)

In [28]:
team_df['elo_value'].values.tolist()

[1694.0,
 1684.0,
 1705.0,
 1627.5,
 1633.0,
 1655.0,
 1653.5,
 1608.5,
 1595.5,
 1613.5,
 1576.5,
 1579.0,
 1543.5,
 1573.0,
 1529.5,
 1524.5,
 1519.0,
 1504.5,
 1510.5,
 1486.0,
 1414.0,
 1487.0]

In [29]:
team_df_testing

,team_abbrev,team_nickname,elo_basic,elo_playoff_full,wins,losses,conference,elo_value,elo_list
0,LAL,Lakers,1678,1710,49,14,western,1694.0,[1694.0]
1,LAC,Clippers,1636,1732,44,20,western,1684.0,[1684.0]
2,MIL,Bucks,1716,1694,53,12,eastern,1705.0,[1705.0]
3,PHI,76ers,1564,1691,39,26,eastern,1627.5,[1627.5]
4,HOU,Rockets,1565,1701,40,24,western,1633.0,[1633.0]
5,BOS,Celtics,1628,1682,43,21,eastern,1655.0,[1655.0]
6,TOR,Raptors,1679,1628,46,18,eastern,1653.5,[1653.5]
7,DEN,Nuggets,1579,1638,43,22,western,1608.5,[1608.5]
8,OKC,Thunder,1608,1583,40,24,western,1595.5,[1595.5]
9,DAL,Mavericks,1584,1643,40,27,western,1613.5,[1613.5]
10,NOP,Pelicans,1542,1611,28,36,western,1576.5,[1576.5]
11,UTA,Jazz,1574,1584,41,23,western,1579.0,[1579.0]
12,MIA,Heat,1553,1534,41,24,eastern,1543.5,[1543.5]
13,IND,Pacers,1560,1586,39,26,eastern,1573.0,[1573.0]
14,POR,Trailblazers,1490,1569,29,37,western,1529.5,[1529.5]
15,ORL,Magic,1503,1546,30,35,eastern,1524.5,[1524.5]
16,BKN,Nets,1478,1560,30,34,eastern,1519.0,[1519.0]
17,MEM,Grizzlies,1553,1456,32,33,western,1504.5,[1504.5]
18,SAC,Kings,1509,1512,28,36,western,1510.5,[1510.5]
19,SAS,Spurs,1499,1473,27,36,western,1486.0,[1486.0]
20,WAS,Wizards,1396,1432,24,40,eastern,1414.0,[1414.0]
21,PHX,Suns,1454,1520,26,39,western,1487.0,[1487.0]

In [30]:
def game_simulation_regular_season(team_a, team_b, input_df):
    ###
    #Get elo values from database
    ###
    elo_a = input_df['elo_list'][input_df['team_abbrev'] == team_a].values[0][-1]
    #print("elo a", elo_a)
    
    elo_b = input_df['elo_list'][input_df['team_abbrev'] == team_b].values[0][-1]
    #print("elo b", elo_b)
    
    # Run elo update and game winner functions
    new_elo_a, new_elo_b, game_winner_output = elo_update(elo_a, elo_b)
    
    # Update elo for first team
    input_df['elo_list'][input_df['team_abbrev'] == team_a].values[0].append(new_elo_a)
    
    # Update elo for second team
    input_df['elo_list'][input_df['team_abbrev'] == team_b].values[0].append(new_elo_b)
    
    # Add wins and losses to respective teams
    if game_winner_output == 1:
        input_df['wins'][input_df['team_abbrev'] == team_a] += 1
        input_df['losses'][input_df['team_abbrev'] == team_b] += 1
    elif game_winner_output == 2:
        input_df['wins'][input_df['team_abbrev'] == team_b] += 1
        input_df['losses'][input_df['team_abbrev'] == team_a] += 1
    else:
        pass
    return input_df

In [32]:
#team_df_testing['elo_list'][team_df_testing['team_abbrev'] == 'LAL'].values[0].append(2000.0)

In [33]:
team_df_testing

,team_abbrev,team_nickname,elo_basic,elo_playoff_full,wins,losses,conference,elo_value,elo_list
0,LAL,Lakers,1678,1710,49,14,western,1694.0,[1694.0]
1,LAC,Clippers,1636,1732,44,20,western,1684.0,[1684.0]
2,MIL,Bucks,1716,1694,53,12,eastern,1705.0,[1705.0]
3,PHI,76ers,1564,1691,39,26,eastern,1627.5,[1627.5]
4,HOU,Rockets,1565,1701,40,24,western,1633.0,[1633.0]
5,BOS,Celtics,1628,1682,43,21,eastern,1655.0,[1655.0]
6,TOR,Raptors,1679,1628,46,18,eastern,1653.5,[1653.5]
7,DEN,Nuggets,1579,1638,43,22,western,1608.5,[1608.5]
8,OKC,Thunder,1608,1583,40,24,western,1595.5,[1595.5]
9,DAL,Mavericks,1584,1643,40,27,western,1613.5,[1613.5]
10,NOP,Pelicans,1542,1611,28,36,western,1576.5,[1576.5]
11,UTA,Jazz,1574,1584,41,23,western,1579.0,[1579.0]
12,MIA,Heat,1553,1534,41,24,eastern,1543.5,[1543.5]
13,IND,Pacers,1560,1586,39,26,eastern,1573.0,[1573.0]
14,POR,Trailblazers,1490,1569,29,37,western,1529.5,[1529.5]
15,ORL,Magic,1503,1546,30,35,eastern,1524.5,[1524.5]
16,BKN,Nets,1478,1560,30,34,eastern,1519.0,[1519.0]
17,MEM,Grizzlies,1553,1456,32,33,western,1504.5,[1504.5]
18,SAC,Kings,1509,1512,28,36,western,1510.5,[1510.5]
19,SAS,Spurs,1499,1473,27,36,western,1486.0,[1486.0]
20,WAS,Wizards,1396,1432,24,40,eastern,1414.0,[1414.0]
21,PHX,Suns,1454,1520,26,39,western,1487.0,[1487.0]

In [34]:
team_df_testing['elo_list'][team_df_testing['team_abbrev'] == 'LAL'].values[-1][-1]

1694.0

In [35]:
# Unit test game_simulation function
game_simulation_regular_season('LAL', 'LAC', team_df_testing)

C:\ProgramFiles\Anaconda2\lib\site-packages\ipykernel_launcher.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\ProgramFiles\Anaconda2\lib\site-packages\ipykernel_launcher.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,team_abbrev,team_nickname,elo_basic,elo_playoff_full,wins,losses,conference,elo_value,elo_list
0,LAL,Lakers,1678,1710,49,15,western,1694.0,"[1694.0, 1683.71225632]"
1,LAC,Clippers,1636,1732,45,20,western,1684.0,"[1684.0, 1694.28774368]"
2,MIL,Bucks,1716,1694,53,12,eastern,1705.0,[1705.0]
3,PHI,76ers,1564,1691,39,26,eastern,1627.5,[1627.5]
4,HOU,Rockets,1565,1701,40,24,western,1633.0,[1633.0]
5,BOS,Celtics,1628,1682,43,21,eastern,1655.0,[1655.0]
6,TOR,Raptors,1679,1628,46,18,eastern,1653.5,[1653.5]
7,DEN,Nuggets,1579,1638,43,22,western,1608.5,[1608.5]
8,OKC,Thunder,1608,1583,40,24,western,1595.5,[1595.5]
9,DAL,Mavericks,1584,1643,40,27,western,1613.5,[1613.5]
10,NOP,Pelicans,1542,1611,28,36,western,1576.5,[1576.5]
11,UTA,Jazz,1574,1584,41,23,western,1579.0,[1579.0]
12,MIA,Heat,1553,1534,41,24,eastern,1543.5,[1543.5]
13,IND,Pacers,1560,1586,39,26,eastern,1573.0,[1573.0]
14,POR,Trailblazers,1490,1569,29,37,western,1529.5,[1529.5]
15,ORL,Magic,1503,1546,30,35,eastern,1524.5,[1524.5]
16,BKN,Nets,1478,1560,30,34,eastern,1519.0,[1519.0]
17,MEM,Grizzlies,1553,1456,32,33,western,1504.5,[1504.5]
18,SAC,Kings,1509,1512,28,36,western,1510.5,[1510.5]
19,SAS,Spurs,1499,1473,27,36,western,1486.0,[1486.0]
20,WAS,Wizards,1396,1432,24,40,eastern,1414.0,[1414.0]
21,PHX,Suns,1454,1520,26,39,western,1487.0,[1487.0]

In [36]:
# Simulate all the regular season games
# Get projected game schedule here:
# https://nba.nbcsports.com/2020/06/03/nba-playoff-schedule-projecting-for-all-22-returning-nba-teams/
# UPDATE: We have an actual schedule
# https://twitter.com/ChrisBHaynes/status/1276655999420526592/photo/1

In [37]:
for index, row in schedule.iterrows():
    game_simulation_regular_season(row['team_a'], row['team_b'], team_df_testing)

In [38]:
def simulate_regular_season(input_df, schedule_df):
    #Possibly update an elo list and append at the end
    for index, row in schedule_df.iterrows():
        game_simulation_regular_season(row['team_a'], row['team_b'], input_df)
    return input_df

In [39]:
team_df_testing['elo_final_regular_season'] = [x[-1] for x in team_df_testing['elo_list']]

In [40]:
team_df_testing

,team_abbrev,team_nickname,elo_basic,elo_playoff_full,wins,losses,conference,elo_value,elo_list,elo_final_regular_season
0,LAL,Lakers,1678,1710,54,18,western,1694.0,"[1694.0, 1683.71225632, 1674.01654934, 1663.42...",1689.496110
1,LAC,Clippers,1636,1732,50,23,western,1684.0,"[1684.0, 1694.28774368, 1703.98345066, 1710.72...",1687.825892
2,MIL,Bucks,1716,1694,54,19,eastern,1705.0,"[1705.0, 1693.57073765, 1681.55154454, 1666.48...",1624.240429
3,PHI,76ers,1564,1691,45,28,eastern,1627.5,"[1627.5, 1635.94410457, 1641.9074918, 1646.500...",1645.885115
4,HOU,Rockets,1565,1701,43,29,western,1633.0,"[1633.0, 1622.43933347, 1634.45852658, 1621.60...",1605.945511
5,BOS,Celtics,1628,1682,48,24,eastern,1655.0,"[1655.0, 1666.42926235, 1672.91211445, 1679.99...",1649.832038
6,TOR,Raptors,1679,1628,51,21,eastern,1653.5,"[1653.5, 1664.08982833, 1651.05836852, 1658.05...",1660.346706
7,DEN,Nuggets,1579,1638,47,26,western,1608.5,"[1608.5, 1596.65067539, 1606.88336745, 1613.41...",1606.593427
8,OKC,Thunder,1608,1583,46,26,western,1595.5,"[1595.5, 1604.73668536, 1594.50399329, 1606.65...",1625.872221
9,DAL,Mavericks,1584,1643,46,29,western,1613.5,"[1613.5, 1624.06066653, 1630.01385154, 1616.70...",1640.981468
10,NOP,Pelicans,1542,1611,32,40,western,1576.5,"[1576.5, 1586.57195454, 1579.82830249, 1587.15...",1565.392844
11,UTA,Jazz,1574,1584,43,29,western,1579.0,"[1579.0, 1568.92804546, 1559.6913601, 1552.591...",1540.134005
12,MIA,Heat,1553,1534,45,28,eastern,1543.5,"[1543.5, 1555.34932461, 1568.38078442, 1561.30...",1553.047854
13,IND,Pacers,1560,1586,45,28,eastern,1573.0,"[1573.0, 1564.55589543, 1571.07045302, 1580.54...",1609.586053
14,POR,Trailblazers,1490,1569,35,39,western,1529.5,"[1529.5, 1538.78168146, 1532.29882936, 1545.15...",1581.835131
15,ORL,Magic,1503,1546,35,39,eastern,1524.5,"[1524.5, 1534.3417105, 1543.61814012, 1552.933...",1543.601724
16,BKN,Nets,1478,1560,31,42,eastern,1519.0,"[1519.0, 1509.1582895, 1499.88185988, 1487.788...",1467.750968
17,MEM,Grizzlies,1553,1456,35,38,western,1504.5,"[1504.5, 1495.21831854, 1484.68593745, 1477.35...",1506.847321
18,SAC,Kings,1509,1512,33,39,western,1510.5,"[1510.5, 1519.79599983, 1510.48058368, 1523.79...",1541.626692
19,SAS,Spurs,1499,1473,29,42,western,1486.0,"[1486.0, 1476.70400017, 1487.23638125, 1481.27...",1466.890485
20,WAS,Wizards,1396,1432,29,43,eastern,1414.0,"[1414.0, 1426.07072637, 1438.16378713, 1431.64...",1467.146282
21,PHX,Suns,1454,1520,26,47,western,1487.0,"[1487.0, 1474.92927363, 1468.97608861, 1464.99...",1435.621723

In [41]:
# Two dimensional dictionary of team and seed
# Sum it up

regular_season_standings = {'team': [], 'seed':[], 'conference':[]}

#pd.DataFrame({'team':[],'seed_1':[], 'seed_2':[], 'seed_3':[], 'seed_4':[], 'seed_5':[], 'seed_6':[], 'seed_7':[], 'seed_8':[],})

In [42]:
for i in ['eastern', 'western']:
    for index, row in team_df_testing[team_df_testing.conference == i].reset_index().reset_index().iterrows():
        regular_season_standings['team'].append(row['team_abbrev'])
        regular_season_standings['conference'].append(row['conference'])
        regular_season_standings['seed'].append(int(row['level_0'] + 1))
        # When looping through season simulations do this:
        # regular_season_standings['iteration'].append(i)

In [48]:
standings_df = pd.DataFrame(regular_season_standings)

standings_df

   conference  seed team
0     eastern     1  MIL
1     eastern     2  PHI
2     eastern     3  BOS
3     eastern     4  TOR
4     eastern     5  MIA
5     eastern     6  IND
6     eastern     7  ORL
7     eastern     8  BKN
8     eastern     9  WAS
9     western     1  LAL
10    western     2  LAC
11    western     3  HOU
12    western     4  DEN
13    western     5  OKC
14    western     6  DAL
15    western     7  NOP
16    western     8  UTA
17    western     9  POR
18    western    10  MEM
19    western    11  SAC
20    western    12  SAS
21    western    13  PHX

In [53]:
pd.pivot_table(standings_df[standings_df.conference == 'western'], values='conference', index=['team'], columns=['seed'], aggfunc=np.count_nonzero)

#Add this sort
# .sort_values(by=2012, ascending=False).index)

seed   1    2    3    4    5    6    7    8    9    10   11   12   13
team
DAL   NaN  NaN  NaN  NaN  NaN  1.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN
DEN   NaN  NaN  NaN  1.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
HOU   NaN  NaN  1.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
LAC   NaN  1.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
LAL   1.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
MEM   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0  NaN  NaN  NaN
NOP   NaN  NaN  NaN  NaN  NaN  NaN  1.0  NaN  NaN  NaN  NaN  NaN  NaN
OKC   NaN  NaN  NaN  NaN  1.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
PHX   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0
POR   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0  NaN  NaN  NaN  NaN
SAC   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0  NaN  NaN
SAS   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0  NaN
UTA   NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0  NaN  NaN  NaN  NaN  NaN

In [ ]:
i = 1
while i < 500:
    # Reset team dataframe with wins/losses and standings
    # Set schedule
    
    # Play regular season games and update team dataframe
    # Append regular_season_standings dataframe with output (will aggregate at the end)
    
    # Do play-in round and get 8 playoff teams (write this to some object)
    # LOW PRIORITY - Append dataframe with list of playoff teams and their seeds (will aggregate at the end)
    
    # Simulate playoffs and append each playoff round to the end of a column (do list comprehension)
    # Take last round made and save that as a variable (do list comphrehension) - second round, conf finals, finals, champion


# Now outside of loop
# Aggregate regular_season_standings
# Aggregate playoff round made and create pandas pivot_table (don't worry about sorting for now)

In [39]:
team_df_testing[team_df_testing.conference == 'eastern'].reset_index().reset_index()

,level_0,index,team_abbrev,team_nickname,elo_basic,elo_playoff_full,wins,losses,conference,elo_value,elo_list,elo_final_regular_season
0,0,2,MIL,Bucks,1716,1694,58,15,eastern,1705.0,"[1705.0, 1713.57073765, 1721.55154454, 1726.46...",1693.291963
1,1,3,PHI,76ers,1564,1691,45,28,eastern,1627.5,"[1627.5, 1615.94410457, 1602.38578024, 1607.44...",1650.901135
2,2,5,BOS,Celtics,1628,1682,46,26,eastern,1655.0,"[1655.0, 1646.42926235, 1653.42639576, 1639.97...",1613.110102
3,3,6,TOR,Raptors,1679,1628,51,21,eastern,1653.5,"[1653.5, 1644.08982833, 1651.05836852, 1637.55...",1662.524108
4,4,12,MIA,Heat,1553,1534,47,26,eastern,1543.5,"[1543.5, 1535.34932461, 1528.38078442, 1541.83...",1594.567978
5,5,13,IND,Pacers,1560,1586,42,31,eastern,1573.0,"[1573.0, 1584.55589543, 1569.67614581, 1578.62...",1553.228435
6,6,15,ORL,Magic,1503,1546,33,41,eastern,1524.5,"[1524.5, 1534.3417105, 1523.61814012, 1532.933...",1503.667754
7,7,16,BKN,Nets,1478,1560,34,39,eastern,1519.0,"[1519.0, 1509.1582895, 1519.88185988, 1526.718...",1521.091977
8,8,20,WAS,Wizards,1396,1432,26,46,eastern,1414.0,"[1414.0, 1406.07072637, 1399.2341256, 1414.113...",1411.124649

In [57]:
team_df_testing['elo_into_playoffs'] = 0.5 * team_df_testing['elo_value'] + 0.5 * team_df_testing['elo_final_regular_season']

In [40]:
type(schedule)

pandas.core.frame.DataFrame

In [41]:
for row in schedule:
    print(row)

team_a
team_b

In [42]:
for a, b in schedule.iterrows():
    print(a)
    print(schedule['team_a'][a])
    #print(team_df[team_df['team_abbrev']==a])
    print(b)

0
UTA
team_a    UTA
team_b    NOP
Name: 0, dtype: object
1
LAC
team_a    LAC
team_b    LAL
Name: 1, dtype: object
2
ORL
team_a    ORL
team_b    BKN
Name: 2, dtype: object
3
ORL
team_a    ORL
team_b    BKN
Name: 3, dtype: object
4
MEM
team_a    MEM
team_b    POR
Name: 4, dtype: object
5
PHX
team_a    PHX
team_b    WAS
Name: 5, dtype: object
6
BOS
team_a    BOS
team_b    MIL
Name: 6, dtype: object
7
SAC
team_a    SAC
team_b    SAS
Name: 7, dtype: object
8
HOU
team_a    HOU
team_b    DAL
Name: 8, dtype: object
9
MIA
team_a    MIA
team_b    DEN
Name: 9, dtype: object
10
UTA
team_a    UTA
team_b    OKC
Name: 10, dtype: object
11
NOP
team_a    NOP
team_b    LAC
Name: 11, dtype: object
12
PHI
team_a    PHI
team_b    IND
Name: 12, dtype: object
13
LAL
team_a    LAL
team_b    TOR
Name: 13, dtype: object
14
WAS
team_a    WAS
team_b    BKN
Name: 14, dtype: object
15
POR
team_a    POR
team_b    BOS
Name: 15, dtype: object
16
SAS
team_a    SAS
team_b    MEM
Name: 16, dtype: object
17
SAC
team_a    SAC
team_b    ORL
Name: 17, dtype: object
18
MIL
team_a    MIL
team_b    HOU
Name: 18, dtype: object
19
DAL
team_a    DAL
team_b    PHX
Name: 19, dtype: object
20
TOR
team_a    TOR
team_b    MIA
Name: 20, dtype: object
21
DEN
team_a    DEN
team_b    OKC
Name: 21, dtype: object
22
IND
team_a    IND
team_b    WAS
Name: 22, dtype: object
23
MEM
team_a    MEM
team_b    NOP
Name: 23, dtype: object
24
SAS
team_a    SAS
team_b    PHI
Name: 24, dtype: object
25
LAL
team_a    LAL
team_b    UTA
Name: 25, dtype: object
26
BKN
team_a    BKN
team_b    MIL
Name: 26, dtype: object
27
DAL
team_a    DAL
team_b    SAC
Name: 27, dtype: object
28
PHX
team_a    PHX
team_b    LAC
Name: 28, dtype: object
29
ORL
team_a    ORL
team_b    IND
Name: 29, dtype: object
30
BOS
team_a    BOS
team_b    MIA
Name: 30, dtype: object
31
HOU
team_a    HOU
team_b    POR
Name: 31, dtype: object
32
MEM
team_a    MEM
team_b    UTA
Name: 32, dtype: object
33
PHI
team_a    PHI
team_b    WAS
Name: 33, dtype: object
34
DEN
team_a    DEN
team_b    SAS
Name: 34, dtype: object
35
OKC
team_a    OKC
team_b    LAL
Name: 35, dtype: object
36
TOR
team_a    TOR
team_b    ORL
Name: 36, dtype: object
37
BKN
team_a    BKN
team_b    BOS
Name: 37, dtype: object
38
NOP
team_a    NOP
team_b    SAC
Name: 38, dtype: object
39
MIA
team_a    MIA
team_b    MIL
Name: 39, dtype: object
40
IND
team_a    IND
team_b    PHX
Name: 40, dtype: object
41
LAC
team_a    LAC
team_b    DAL
Name: 41, dtype: object
42
POR
team_a    POR
team_b    DEN
Name: 42, dtype: object
43
LAL
team_a    LAL
team_b    HOU
Name: 43, dtype: object
44
UTA
team_a    UTA
team_b    SAS
Name: 44, dtype: object
45
OKC
team_a    OKC
team_b    MEM
Name: 45, dtype: object
46
SAC
team_a    SAC
team_b    BKN
Name: 46, dtype: object
47
ORL
team_a    ORL
team_b    PHI
Name: 47, dtype: object
48
WAS
team_a    WAS
team_b    NOP
Name: 48, dtype: object
49
BOS
team_a    BOS
team_b    TOR
Name: 49, dtype: object
50
LAC
team_a    LAC
team_b    POR
Name: 50, dtype: object
51
UTA
team_a    UTA
team_b    DEN
Name: 51, dtype: object
52
LAL
team_a    LAL
team_b    IND
Name: 52, dtype: object
53
PHX
team_a    PHX
team_b    MIA
Name: 53, dtype: object
54
MIL
team_a    MIL
team_b    DAL
Name: 54, dtype: object
55
WAS
team_a    WAS
team_b    OKC
Name: 55, dtype: object
56
MEM
team_a    MEM
team_b    TOR
Name: 56, dtype: object
57
SAS
team_a    SAS
team_b    NOP
Name: 57, dtype: object
58
ORL
team_a    ORL
team_b    BOS
Name: 58, dtype: object
59
PHI
team_a    PHI
team_b    POR
Name: 59, dtype: object
60
HOU
team_a    HOU
team_b    SAC
Name: 60, dtype: object
61
BKN
team_a    BKN
team_b    LAC
Name: 61, dtype: object
62
OKC
team_a    OKC
team_b    PHX
Name: 62, dtype: object
63
DAL
team_a    DAL
team_b    UTA
Name: 63, dtype: object
64
TOR
team_a    TOR
team_b    MIL
Name: 64, dtype: object
65
IND
team_a    IND
team_b    MIA
Name: 65, dtype: object
66
DEN
team_a    DEN
team_b    LAL
Name: 66, dtype: object
67
BKN
team_a    BKN
team_b    ORL
Name: 67, dtype: object
68
HOU
team_a    HOU
team_b    SAS
Name: 68, dtype: object
69
PHX
team_a    PHX
team_b    PHI
Name: 69, dtype: object
70
POR
team_a    POR
team_b    DAL
Name: 70, dtype: object
71
BOS
team_a    BOS
team_b    MEM
Name: 71, dtype: object
72
NOP
team_a    NOP
team_b    SAC
Name: 72, dtype: object
73
MIL
team_a    MIL
team_b    WAS
Name: 73, dtype: object
74
IND
team_a    IND
team_b    HOU
Name: 74, dtype: object
75
TOR
team_a    TOR
team_b    PHI
Name: 75, dtype: object
76
MIA
team_a    MIA
team_b    OKC
Name: 76, dtype: object
77
LAC
team_a    LAC
team_b    DEN
Name: 77, dtype: object
78
WAS
team_a    WAS
team_b    BOS
Name: 78, dtype: object
79
POR
team_a    POR
team_b    BKN
Name: 79, dtype: object
80
SAC
team_a    SAC
team_b    LAL
Name: 80, dtype: object
81
MIL
team_a    MIL
team_b    MEM
Name: 81, dtype: object
82
NOP
team_a    NOP
team_b    ORL
Name: 82, dtype: object
83
DAL
team_a    DAL
team_b    PHX
Name: 83, dtype: object
84
SAS
team_a    SAS
team_b    UTA
Name: 84, dtype: object
85
PHI
team_a    PHI
team_b    HOU
Name: 85, dtype: object
86
MIA
team_a    MIA
team_b    IND
Name: 86, dtype: object
87
OKC
team_a    OKC
team_b    LAC
Name: 87, dtype: object
88
DEN
team_a    DEN
team_b    TOR
Name: 88, dtype: object

In [43]:
team_df[team_df['team_abbrev'] == 'LAL']

,team_abbrev,team_nickname,elo_basic,elo_playoff_full,wins,losses,conference,elo_value,elo_list,elo_final_regular_season
0,LAL,Lakers,1678,1710,56,16,western,1694.0,"[1694.0, 1683.71225632, 1674.01654934, 1683.42...",1724.181604

In [44]:
team_df

,team_abbrev,team_nickname,elo_basic,elo_playoff_full,wins,losses,conference,elo_value,elo_list,elo_final_regular_season
0,LAL,Lakers,1678,1710,56,16,western,1694.0,"[1694.0, 1683.71225632, 1674.01654934, 1683.42...",1724.181604
1,LAC,Clippers,1636,1732,51,22,western,1684.0,"[1684.0, 1694.28774368, 1703.98345066, 1710.22...",1703.862966
2,MIL,Bucks,1716,1694,58,15,eastern,1705.0,"[1705.0, 1713.57073765, 1721.55154454, 1726.46...",1693.291963
3,PHI,76ers,1564,1691,45,28,eastern,1627.5,"[1627.5, 1615.94410457, 1602.38578024, 1607.44...",1650.901135
4,HOU,Rockets,1565,1701,43,29,western,1633.0,"[1633.0, 1642.43933347, 1634.45852658, 1641.58...",1604.060336
5,BOS,Celtics,1628,1682,46,26,eastern,1655.0,"[1655.0, 1646.42926235, 1653.42639576, 1639.97...",1613.110102
6,TOR,Raptors,1679,1628,51,21,eastern,1653.5,"[1653.5, 1644.08982833, 1651.05836852, 1637.55...",1662.524108
7,DEN,Nuggets,1579,1638,46,27,western,1608.5,"[1608.5, 1616.65067539, 1625.75108174, 1632.28...",1586.534914
8,OKC,Thunder,1608,1583,43,29,western,1595.5,"[1595.5, 1585.3108665, 1576.21046015, 1569.400...",1574.761197
9,DAL,Mavericks,1584,1643,42,33,western,1613.5,"[1613.5, 1604.06066653, 1591.01899343, 1578.20...",1575.261187
10,NOP,Pelicans,1542,1611,33,39,western,1576.5,"[1576.5, 1566.57195454, 1560.33289258, 1568.76...",1585.315911
11,UTA,Jazz,1574,1584,48,24,western,1579.0,"[1579.0, 1588.92804546, 1599.11717896, 1591.49...",1631.234866
12,MIA,Heat,1553,1534,47,26,eastern,1543.5,"[1543.5, 1535.34932461, 1528.38078442, 1541.83...",1594.567978
13,IND,Pacers,1560,1586,42,31,eastern,1573.0,"[1573.0, 1584.55589543, 1569.67614581, 1578.62...",1553.228435
14,POR,Trailblazers,1490,1569,32,42,western,1529.5,"[1529.5, 1538.78168146, 1531.78454805, 1524.65...",1523.966998
15,ORL,Magic,1503,1546,33,41,eastern,1524.5,"[1524.5, 1534.3417105, 1523.61814012, 1532.933...",1503.667754
16,BKN,Nets,1478,1560,34,39,eastern,1519.0,"[1519.0, 1509.1582895, 1519.88185988, 1526.718...",1521.091977
17,MEM,Grizzlies,1553,1456,35,38,western,1504.5,"[1504.5, 1495.21831854, 1505.26107963, 1496.83...",1506.238907
18,SAC,Kings,1509,1512,31,41,western,1510.5,"[1510.5, 1499.79599983, 1490.48058368, 1503.29...",1507.146315
19,SAS,Spurs,1499,1473,30,41,western,1486.0,"[1486.0, 1496.70400017, 1486.66123907, 1500.21...",1487.230554
20,WAS,Wizards,1396,1432,26,46,eastern,1414.0,"[1414.0, 1406.07072637, 1399.2341256, 1414.113...",1411.124649
21,PHX,Suns,1454,1520,30,43,western,1487.0,"[1487.0, 1494.92927363, 1507.97094673, 1503.21...",1503.196143

In [45]:
# Create win percentage column
team_df['win_percentage'] = team_df['wins']/(team_df['wins']+team_df['losses'])

In [46]:
# Create conference specific dataframes
df_western = team_df[team_df['conference'] == 'western']
df_eastern = team_df[team_df['conference'] == 'eastern']

In [47]:
# Get Western standings at the end of the regular season
df_western['standing_min'] = df_western['win_percentage'].rank(method='min', ascending=False)
df_western['standing_dense'] = df_western['win_percentage'].rank(method='dense', ascending=False)
df_western['standing_random'] = df_western['win_percentage'].rank(method='first', ascending=False)
df_western.sort_values(by=['standing_min', 'standing_random'], inplace=True)
df_western.reset_index(inplace=True)
df_western['ahead_wins'] = df_western['wins'].shift(1)
df_western['ahead_losses'] = df_western['losses'].shift(1)

df_western['games_back_of_ahead_team'] = ((df_western['ahead_wins'] - df_western['wins']) + (df_western['losses'] - df_western['ahead_losses']))/2

C:\ProgramFiles\Anaconda2\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\ProgramFiles\Anaconda2\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\ProgramFiles\Anaconda2\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
C:\ProgramFiles\Anaconda2\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
C:\ProgramFiles\Anaconda2\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
C:\ProgramFiles\Anaconda2\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\ProgramFiles\Anaconda2\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.

In [48]:
df_western

,index,team_abbrev,team_nickname,elo_basic,elo_playoff_full,wins,losses,conference,elo_value,elo_list,elo_final_regular_season,win_percentage,standing_min,standing_dense,standing_random,ahead_wins,ahead_losses,games_back_of_ahead_team
0,0,LAL,Lakers,1678,1710,56,16,western,1694.0,"[1694.0, 1683.71225632, 1674.01654934, 1683.42...",1724.181604,0.777778,1.0,1.0,1.0,NaN,NaN,NaN
1,1,LAC,Clippers,1636,1732,51,22,western,1684.0,"[1684.0, 1694.28774368, 1703.98345066, 1710.22...",1703.862966,0.698630,2.0,2.0,2.0,56.0,16.0,5.5
2,11,UTA,Jazz,1574,1584,48,24,western,1579.0,"[1579.0, 1588.92804546, 1599.11717896, 1591.49...",1631.234866,0.666667,3.0,3.0,3.0,51.0,22.0,2.5
3,7,DEN,Nuggets,1579,1638,46,27,western,1608.5,"[1608.5, 1616.65067539, 1625.75108174, 1632.28...",1586.534914,0.630137,4.0,4.0,4.0,48.0,24.0,2.5
4,4,HOU,Rockets,1565,1701,43,29,western,1633.0,"[1633.0, 1642.43933347, 1634.45852658, 1641.58...",1604.060336,0.597222,5.0,5.0,5.0,46.0,27.0,2.5
5,8,OKC,Thunder,1608,1583,43,29,western,1595.5,"[1595.5, 1585.3108665, 1576.21046015, 1569.400...",1574.761197,0.597222,5.0,5.0,6.0,43.0,29.0,0.0
6,9,DAL,Mavericks,1584,1643,42,33,western,1613.5,"[1613.5, 1604.06066653, 1591.01899343, 1578.20...",1575.261187,0.560000,7.0,6.0,7.0,43.0,29.0,2.5
7,17,MEM,Grizzlies,1553,1456,35,38,western,1504.5,"[1504.5, 1495.21831854, 1505.26107963, 1496.83...",1506.238907,0.479452,8.0,7.0,8.0,42.0,33.0,6.0
8,10,NOP,Pelicans,1542,1611,33,39,western,1576.5,"[1576.5, 1566.57195454, 1560.33289258, 1568.76...",1585.315911,0.458333,9.0,8.0,9.0,35.0,38.0,1.5
9,14,POR,Trailblazers,1490,1569,32,42,western,1529.5,"[1529.5, 1538.78168146, 1531.78454805, 1524.65...",1523.966998,0.432432,10.0,9.0,10.0,33.0,39.0,2.0
10,18,SAC,Kings,1509,1512,31,41,western,1510.5,"[1510.5, 1499.79599983, 1490.48058368, 1503.29...",1507.146315,0.430556,11.0,10.0,11.0,32.0,42.0,0.0
11,19,SAS,Spurs,1499,1473,30,41,western,1486.0,"[1486.0, 1496.70400017, 1486.66123907, 1500.21...",1487.230554,0.422535,12.0,11.0,12.0,31.0,41.0,0.5
12,21,PHX,Suns,1454,1520,30,43,western,1487.0,"[1487.0, 1494.92927363, 1507.97094673, 1503.21...",1503.196143,0.410959,13.0,12.0,13.0,30.0,41.0,1.0

In [49]:
# Get Eastern standings at the end of the regular season
df_eastern['standing_min'] = df_eastern['win_percentage'].rank(method='min', ascending=False)
df_eastern['standing_dense'] = df_eastern['win_percentage'].rank(method='dense', ascending=False)
df_eastern['standing_random'] = df_eastern['win_percentage'].rank(method='first', ascending=False)
df_eastern.sort_values(by=['standing_min', 'standing_random'], inplace=True)
df_eastern.reset_index(inplace=True)
df_eastern['ahead_wins'] = df_eastern['wins'].shift(1)
df_eastern['ahead_losses'] = df_eastern['losses'].shift(1)

df_eastern['games_back_of_ahead_team'] = ((df_eastern['ahead_wins'] - df_eastern['wins']) + (df_eastern['losses'] - df_eastern['ahead_losses']))/2

C:\ProgramFiles\Anaconda2\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\ProgramFiles\Anaconda2\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\ProgramFiles\Anaconda2\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
C:\ProgramFiles\Anaconda2\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
C:\ProgramFiles\Anaconda2\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
C:\ProgramFiles\Anaconda2\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\ProgramFiles\Anaconda2\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.

In [50]:
def bracket_cleaner(input_df):
    input_df['standing_min'] = input_df['win_percentage'].rank(method='min', ascending=False)
    input_df['standing_dense'] = input_df['win_percentage'].rank(method='dense', ascending=False)
    input_df['standing_random'] = input_df['win_percentage'].rank(method='first', ascending=False)
    input_df.sort_values(by=['standing_min', 'standing_random'], inplace=True)
    input_df.reset_index(inplace=True)
    input_df['ahead_wins'] = input_df['wins'].shift(1)
    input_df['ahead_losses'] = input_df['losses'].shift(1)
    input_df['games_back_of_ahead_team'] = ((input_df['ahead_wins'] - input_df['wins']) + (input_df['losses'] - input_df['ahead_losses']))/2
    return input_df

In [51]:
# Create series for each Western seed 1-7 and Eastern seed 1-7
west_seed_one = df_western.loc[0]
west_seed_two = df_western.loc[1]
west_seed_three = df_western.loc[2]
west_seed_four = df_western.loc[3]
west_seed_five = df_western.loc[4]
west_seed_six = df_western.loc[5]
west_seed_seven = df_western.loc[6]
east_seed_one = df_eastern.loc[0]
east_seed_two = df_eastern.loc[1]
east_seed_three = df_eastern.loc[2]
east_seed_four = df_eastern.loc[3]
east_seed_five = df_eastern.loc[4]
east_seed_six = df_eastern.loc[5]
east_seed_seven = df_eastern.loc[6]

In [52]:
# Play-in round function
def play_in_round(input_df):
    eight = input_df.loc[7]
    nine = input_df.loc[8]
    if nine['games_back_of_ahead_team'] > 4:
        return eight
    elif nine['games_back_of_ahead_team'] <= 4:
        rating1_1, rating2_1, outcome1 = elo_update(eight['elo_value'], nine['elo_value'])
        eight['elo_value'] = rating1_1
        nine['elo_value'] = rating2_1
        if outcome1 == 1:
            return eight
        else:
            rating1_2, rating2_2, outcome2 = elo_update(eight['elo_value'], nine['elo_value'])
            eight['elo_value'] = rating1_2
            nine['elo_value'] = rating2_2
            if outcome2 == 1:
                return eight
            else:
                return nine

In [53]:
# Unit test play in round function
df_western_test = df_western
final_west_team = play_in_round(df_western_test)
print(final_west_team)

index                                                                      17
team_abbrev                                                               MEM
team_nickname                                                       Grizzlies
elo_basic                                                                1553
elo_playoff_full                                                         1456
wins                                                                       35
losses                                                                     38
conference                                                            western
elo_value                                                             1509.02
elo_list                    [1504.5, 1495.21831854, 1505.26107963, 1496.83...
elo_final_regular_season                                              1506.24
win_percentage                                                       0.479452
standing_min                                                                8
standing_dense                                                              7
standing_random                                                             8
ahead_wins                                                                 42
ahead_losses                                                               33
games_back_of_ahead_team                                                    6
Name: 7, dtype: object

C:\ProgramFiles\Anaconda2\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
C:\ProgramFiles\Anaconda2\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.
C:\ProgramFiles\Anaconda2\lib\site-packages\ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
C:\ProgramFiles\Anaconda2\lib\site-packages\ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()

In [54]:
# Assign final playoff spots
west_seed_eight = play_in_round(df_western)

C:\ProgramFiles\Anaconda2\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
C:\ProgramFiles\Anaconda2\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.
C:\ProgramFiles\Anaconda2\lib\site-packages\ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
C:\ProgramFiles\Anaconda2\lib\site-packages\ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()

In [55]:
west_seed_eight

index                                                                      10
team_abbrev                                                               NOP
team_nickname                                                        Pelicans
elo_basic                                                                1542
elo_playoff_full                                                         1611
wins                                                                       33
losses                                                                     39
conference                                                            western
elo_value                                                             1591.98
elo_list                    [1576.5, 1566.57195454, 1560.33289258, 1568.76...
elo_final_regular_season                                              1585.32
win_percentage                                                       0.458333
standing_min                                                                9
standing_dense                                                              8
standing_random                                                             9
ahead_wins                                                                 35
ahead_losses                                                               38
games_back_of_ahead_team                                                  1.5
Name: 8, dtype: object

In [56]:
df_eastern

,index,team_abbrev,team_nickname,elo_basic,elo_playoff_full,wins,losses,conference,elo_value,elo_list,elo_final_regular_season,win_percentage,standing_min,standing_dense,standing_random,ahead_wins,ahead_losses,games_back_of_ahead_team
0,2,MIL,Bucks,1716,1694,58,15,eastern,1705.0,"[1705.0, 1713.57073765, 1721.55154454, 1726.46...",1693.291963,0.794521,1.0,1.0,1.0,NaN,NaN,NaN
1,6,TOR,Raptors,1679,1628,51,21,eastern,1653.5,"[1653.5, 1644.08982833, 1651.05836852, 1637.55...",1662.524108,0.708333,2.0,2.0,2.0,58.0,15.0,6.5
2,12,MIA,Heat,1553,1534,47,26,eastern,1543.5,"[1543.5, 1535.34932461, 1528.38078442, 1541.83...",1594.567978,0.643836,3.0,3.0,3.0,51.0,21.0,4.5
3,5,BOS,Celtics,1628,1682,46,26,eastern,1655.0,"[1655.0, 1646.42926235, 1653.42639576, 1639.97...",1613.110102,0.638889,4.0,4.0,4.0,47.0,26.0,0.5
4,3,PHI,76ers,1564,1691,45,28,eastern,1627.5,"[1627.5, 1615.94410457, 1602.38578024, 1607.44...",1650.901135,0.616438,5.0,5.0,5.0,46.0,26.0,1.5
5,13,IND,Pacers,1560,1586,42,31,eastern,1573.0,"[1573.0, 1584.55589543, 1569.67614581, 1578.62...",1553.228435,0.575342,6.0,6.0,6.0,45.0,28.0,3.0
6,16,BKN,Nets,1478,1560,34,39,eastern,1519.0,"[1519.0, 1509.1582895, 1519.88185988, 1526.718...",1521.091977,0.465753,7.0,7.0,7.0,42.0,31.0,8.0
7,15,ORL,Magic,1503,1546,33,41,eastern,1524.5,"[1524.5, 1534.3417105, 1523.61814012, 1532.933...",1503.667754,0.445946,8.0,8.0,8.0,34.0,39.0,1.5
8,20,WAS,Wizards,1396,1432,26,46,eastern,1414.0,"[1414.0, 1406.07072637, 1399.2341256, 1414.113...",1411.124649,0.361111,9.0,9.0,9.0,33.0,41.0,6.0

In [57]:
east_seed_eight = play_in_round(df_eastern)

In [58]:
#Simulate playoff series
def playoff_series_sim(team_one, team_two):
    team1_wins = 0
    team2_wins = 0
    while team1_wins < 4 and team2_wins < 4:
        rating1, rating2, outcome = elo_update(team_one['elo_value'], team_two['elo_value'])
        team_one['elo_value'] = rating1
        team_two['elo_value'] = rating2
        if outcome == 1:
            team1_wins += 1
        elif outcome == 2:
            team2_wins += 1
    if team1_wins == 4:
        return team_one
    elif team2_wins == 4:
        return team_two
    else:
        return None

In [59]:
winnerofseries = playoff_series_sim(west_seed_eight, east_seed_eight)

C:\ProgramFiles\Anaconda2\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
C:\ProgramFiles\Anaconda2\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [60]:
winnerofseries

index                                                                      15
team_abbrev                                                               ORL
team_nickname                                                           Magic
elo_basic                                                                1503
elo_playoff_full                                                         1546
wins                                                                       33
losses                                                                     41
conference                                                            eastern
elo_value                                                             1561.87
elo_list                    [1524.5, 1534.3417105, 1523.61814012, 1532.933...
elo_final_regular_season                                              1503.67
win_percentage                                                       0.445946
standing_min                                                                8
standing_dense                                                              8
standing_random                                                             8
ahead_wins                                                                 34
ahead_losses                                                               39
games_back_of_ahead_team                                                  1.5
Name: 7, dtype: object

In [61]:
#Western playoffs
west18 = playoff_series_sim(west_seed_one, west_seed_eight)
west27 = playoff_series_sim(west_seed_two, west_seed_seven)
west36 = playoff_series_sim(west_seed_three, west_seed_six)
west45 = playoff_series_sim(west_seed_four, west_seed_five)
westsemi1 = playoff_series_sim(west18, west45)
print(westsemi1)
westsemi2 = playoff_series_sim(west27, west36)
print(westsemi2)
westfinals = playoff_series_sim(westsemi1, westsemi2)

C:\ProgramFiles\Anaconda2\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
C:\ProgramFiles\Anaconda2\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

KeyboardInterrupt:

In [ ]:
#Eastern playoffs
east18 = playoff_series_sim(east_seed_one, east_seed_eight)
east27 = playoff_series_sim(east_seed_two, east_seed_seven)
east36 = playoff_series_sim(east_seed_three, east_seed_six)
east45 = playoff_series_sim(east_seed_four, east_seed_five)
eastsemi1 = playoff_series_sim(east18, east45)
print(eastsemi1)
eastsemi2 = playoff_series_sim(east27, east36)
print(eastsemi2)
eastfinals = playoff_series_sim(eastsemi1, eastsemi2)

In [ ]:
print(westfinals)
print(eastfinals)

In [ ]:
#NBA Finals
champion = playoff_series_sim(westfinals, eastfinals)

In [ ]:
print(champion)

In [ ]:
#Create counting variable and list to place champions
i = 1
champions_list = []
iterations = 50

while i <= iterations:    
    # Reset season to start
    team_df = team_df_backup
    
    # Do all the season steps
    team_df = all_regular_season(team_df)
    
    # Add win percentage
    team_df['win_percentage'] = team_df['wins']/(team_df['wins']+team_df['losses'])
    
    # Create conference specific dataframes
    df_western = team_df[team_df['conference'] == 'western']
    df_eastern = team_df[team_df['conference'] == 'eastern']
    df_western = bracket_cleaner(df_western)
    df_eastern = bracket_cleaner(df_eastern)
    
    # Create conference seeds
    west_seed_one = df_western.loc[0]
    west_seed_two = df_western.loc[1]
    west_seed_three = df_western.loc[2]
    west_seed_four = df_western.loc[3]
    west_seed_five = df_western.loc[4]
    west_seed_six = df_western.loc[5]
    west_seed_seven = df_western.loc[6]
    west_seed_eight = play_in_round(df_western)
    east_seed_one = df_eastern.loc[0]
    east_seed_two = df_eastern.loc[1]
    east_seed_three = df_eastern.loc[2]
    east_seed_four = df_eastern.loc[3]
    east_seed_five = df_eastern.loc[4]
    east_seed_six = df_eastern.loc[5]
    east_seed_seven = df_eastern.loc[6]
    east_seed_eight = play_in_round(df_eastern)
   
    # Simulate Western playoffs
    west18 = playoff_series_sim(west_seed_one, west_seed_eight)
    west27 = playoff_series_sim(west_seed_two, west_seed_seven)
    west36 = playoff_series_sim(west_seed_three, west_seed_six)
    west45 = playoff_series_sim(west_seed_four, west_seed_five)
    westsemi1 = playoff_series_sim(west18, west45)
    westsemi2 = playoff_series_sim(west27, west36)
    westfinals = playoff_series_sim(westsemi1, westsemi2)

    # Simulate Eastern playoffs
    east18 = playoff_series_sim(east_seed_one, east_seed_eight)
    east27 = playoff_series_sim(east_seed_two, east_seed_seven)
    east36 = playoff_series_sim(east_seed_three, east_seed_six)
    east45 = playoff_series_sim(east_seed_four, east_seed_five)
    eastsemi1 = playoff_series_sim(east18, east45)
    eastsemi2 = playoff_series_sim(east27, east36)
    eastfinals = playoff_series_sim(eastsemi1, eastsemi2)

    champion_winner = playoff_series_sim(westfinals, eastfinals)
    champion = champion_winner['team_abbrev']

    
    # Append champions list
    champions_list.append(champion)
    
    # Increase counter
    i += 1

In [ ]:
# Get counts of champions
Counter(champions_list)